// <auto-generated />
using System;
using System.Collections.Generic;
using Infra.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infra.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260722150634_AddTemplatesAndWorkouts")]
    partial class AddTemplatesAndWorkouts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Exercises.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DefaultIntervalRestSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("default_interval_rest_seconds");

                    b.Property<int>("DefaultReps")
                        .HasColumnType("integer")
                        .HasColumnName("default_reps");

                    b.Property<int>("DefaultRestSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("default_rest_seconds");

                    b.Property<int?>("DefaultRounds")
                        .HasColumnType("integer")
                        .HasColumnName("default_rounds");

                    b.Property<int>("DefaultSets")
                        .HasColumnType("integer")
                        .HasColumnName("default_sets");

                    b.Property<int?>("DefaultWorkSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("default_work_seconds");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsAerobic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_aerobic");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("PrimaryMuscleGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_muscle_group_id");

                    b.PrimitiveCollection<List<Guid>>("SecondaryMuscleGroupIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("secondary_muscle_group_ids");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UsageExample")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("usage_example");

                    b.HasKey("Id")
                        .HasName("pk_exercises");

                    b.HasIndex("TenantId", "Category")
                        .HasDatabaseName("ix_exercises_tenant_id_category");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_exercises_tenant_id_id");

                    b.ToTable("exercises", "public");
                });

            modelBuilder.Entity("Domain.Exercises.ExerciseMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_type");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("storage_key");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_exercise_media");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("ix_exercise_media_exercise_id");

                    b.ToTable("exercise_media", "public");
                });

            modelBuilder.Entity("Domain.MuscleGroups.MuscleGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyRegion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("body_region");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_muscle_groups");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_muscle_groups_name");

                    b.ToTable("muscle_groups", "public");
                });

            modelBuilder.Entity("Domain.SampleEntities.SampleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_sample_entities");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_sample_entities_tenant_id_id");

                    b.ToTable("sample_entities", "public");
                });

            modelBuilder.Entity("Domain.Workouts.TemplateItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatorNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("creator_notes");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<int?>("IntervalRestSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("interval_rest_seconds");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("Reps")
                        .HasColumnType("integer")
                        .HasColumnName("reps");

                    b.Property<int>("RestSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("rest_seconds");

                    b.Property<int?>("Rounds")
                        .HasColumnType("integer")
                        .HasColumnName("rounds");

                    b.Property<string>("SectionLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("section_label");

                    b.Property<int>("Sets")
                        .HasColumnType("integer")
                        .HasColumnName("sets");

                    b.Property<int?>("WorkSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("work_seconds");

                    b.Property<Guid>("WorkoutTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_template_id");

                    b.HasKey("Id")
                        .HasName("pk_template_items");

                    b.HasIndex("WorkoutTemplateId")
                        .HasDatabaseName("ix_template_items_workout_template_id");

                    b.ToTable("template_items", "public");
                });

            modelBuilder.Entity("Domain.Workouts.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerStudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_student_id");

                    b.Property<Guid?>("SourceTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_template_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_workouts");

                    b.HasIndex("TenantId", "OwnerStudentId")
                        .HasDatabaseName("ix_workouts_tenant_id_owner_student_id");

                    b.ToTable("workouts", "public");
                });

            modelBuilder.Entity("Domain.Workouts.WorkoutItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<int?>("IntervalRestSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("interval_rest_seconds");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("ProfessorComment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("professor_comment");

                    b.Property<int>("Reps")
                        .HasColumnType("integer")
                        .HasColumnName("reps");

                    b.Property<int>("RestSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("rest_seconds");

                    b.Property<int?>("Rounds")
                        .HasColumnType("integer")
                        .HasColumnName("rounds");

                    b.Property<string>("SectionLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("section_label");

                    b.Property<int>("Sets")
                        .HasColumnType("integer")
                        .HasColumnName("sets");

                    b.Property<int?>("WorkSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("work_seconds");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_id");

                    b.HasKey("Id")
                        .HasName("pk_workout_items");

                    b.HasIndex("WorkoutId")
                        .HasDatabaseName("ix_workout_items_workout_id");

                    b.ToTable("workout_items", "public");
                });

            modelBuilder.Entity("Domain.Workouts.WorkoutTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatorNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("creator_notes");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_workout_templates");

                    b.HasIndex("TenantId", "IsSystemDefault")
                        .HasDatabaseName("ix_workout_templates_tenant_id_is_system_default");

                    b.ToTable("workout_templates", "public");
                });

            modelBuilder.Entity("Domain.Exercises.ExerciseMedia", b =>
                {
                    b.HasOne("Domain.Exercises.Exercise", null)
                        .WithMany("Media")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_media_exercises_exercise_id");
                });

            modelBuilder.Entity("Domain.Workouts.TemplateItem", b =>
                {
                    b.HasOne("Domain.Workouts.WorkoutTemplate", null)
                        .WithMany("Items")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_items_workout_templates_workout_template_id");
                });

            modelBuilder.Entity("Domain.Workouts.WorkoutItem", b =>
                {
                    b.HasOne("Domain.Workouts.Workout", null)
                        .WithMany("Items")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workout_items_workouts_workout_id");
                });

            modelBuilder.Entity("Domain.Exercises.Exercise", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("Domain.Workouts.Workout", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Domain.Workouts.WorkoutTemplate", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
