// <auto-generated />
using System;
using System.Collections.Generic;
using Infra.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infra.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Devices.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("platform");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_device_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_device_tokens_token");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("ix_device_tokens_tenant_id_user_id");

                    b.ToTable("device_tokens", "public");
                });

            modelBuilder.Entity("Domain.Execution.ExerciseNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<decimal?>("LoadKg")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("load_kg");

                    b.Property<bool>("PainFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("pain_flag");

                    b.Property<string>("PainNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("pain_note");

                    b.Property<int?>("PerformedReps")
                        .HasColumnType("integer")
                        .HasColumnName("performed_reps");

                    b.Property<int?>("PerformedSets")
                        .HasColumnType("integer")
                        .HasColumnName("performed_sets");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkoutItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_item_id");

                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_session_id");

                    b.HasKey("Id")
                        .HasName("pk_exercise_notes");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("ix_exercise_notes_exercise_id");

                    b.HasIndex("WorkoutSessionId")
                        .HasDatabaseName("ix_exercise_notes_workout_session_id");

                    b.HasIndex("WorkoutSessionId", "WorkoutItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_exercise_notes_workout_session_id_workout_item_id");

                    b.ToTable("exercise_notes", "public");
                });

            modelBuilder.Entity("Domain.Execution.WorkoutSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_id");

                    b.HasKey("Id")
                        .HasName("pk_workout_schedules");

                    b.HasIndex("TenantId", "StudentId", "ScheduledDate")
                        .HasDatabaseName("ix_workout_schedules_tenant_id_student_id_scheduled_date");

                    b.ToTable("workout_schedules", "public");
                });

            modelBuilder.Entity("Domain.Execution.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int?>("CompletionRating")
                        .HasColumnType("integer")
                        .HasColumnName("completion_rating");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("OverallComment")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("overall_comment");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_id");

                    b.HasKey("Id")
                        .HasName("pk_workout_sessions");

                    b.HasIndex("TenantId", "StudentId", "WorkoutId", "StartedAt")
                        .HasDatabaseName("ix_workout_sessions_tenant_id_student_id_workout_id_started_at");

                    b.ToTable("workout_sessions", "public");
                });

            modelBuilder.Entity("Domain.Exercises.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DefaultIntervalRestSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("default_interval_rest_seconds");

                    b.Property<int>("DefaultReps")
                        .HasColumnType("integer")
                        .HasColumnName("default_reps");

                    b.Property<int>("DefaultRestSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("default_rest_seconds");

                    b.Property<int?>("DefaultRounds")
                        .HasColumnType("integer")
                        .HasColumnName("default_rounds");

                    b.Property<int>("DefaultSets")
                        .HasColumnType("integer")
                        .HasColumnName("default_sets");

                    b.Property<int?>("DefaultWorkSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("default_work_seconds");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsAerobic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_aerobic");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("ModalityId")
                        .HasColumnType("uuid")
                        .HasColumnName("modality_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("PrimaryMuscleGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_muscle_group_id");

                    b.PrimitiveCollection<List<Guid>>("SecondaryMuscleGroupIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("secondary_muscle_group_ids");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UsageExample")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("usage_example");

                    b.HasKey("Id")
                        .HasName("pk_exercises");

                    b.HasIndex("ModalityId")
                        .HasDatabaseName("ix_exercises_modality_id");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_exercises_tenant_id_id");

                    b.HasIndex("TenantId", "ModalityId")
                        .HasDatabaseName("ix_exercises_tenant_id_modality_id");

                    b.ToTable("exercises", "public");
                });

            modelBuilder.Entity("Domain.Exercises.ExerciseMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_type");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("storage_key");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_exercise_media");

                    b.HasIndex("ExerciseId")
                        .HasDatabaseName("ix_exercise_media_exercise_id");

                    b.ToTable("exercise_media", "public");
                });

            modelBuilder.Entity("Domain.Modalities.Modality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("color_hex");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsIntervalBased")
                        .HasColumnType("boolean")
                        .HasColumnName("is_interval_based");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_modalities");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_modalities_name");

                    b.ToTable("modalities", "public");
                });

            modelBuilder.Entity("Domain.MuscleGroups.MuscleGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyRegion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("body_region");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_muscle_groups");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_muscle_groups_name");

                    b.ToTable("muscle_groups", "public");
                });

            modelBuilder.Entity("Domain.SampleEntities.SampleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_sample_entities");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_sample_entities_tenant_id_id");

                    b.ToTable("sample_entities", "public");
                });

            modelBuilder.Entity("Domain.Students.HealthObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("detail");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_profile_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_health_observations");

                    b.HasIndex("StudentProfileId")
                        .HasDatabaseName("ix_health_observations_student_profile_id");

                    b.ToTable("health_observations", "public");
                });

            modelBuilder.Entity("Domain.Students.StudentNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("author_name");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_profile_id");

                    b.HasKey("Id")
                        .HasName("pk_student_notes");

                    b.HasIndex("StudentProfileId")
                        .HasDatabaseName("ix_student_notes_student_profile_id");

                    b.ToTable("student_notes", "public");
                });

            modelBuilder.Entity("Domain.Students.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Goals")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("goals");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_student_profiles");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_profiles_tenant_id_user_id");

                    b.ToTable("student_profiles", "public");
                });

            modelBuilder.Entity("Domain.Workouts.TemplateItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatorNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("creator_notes");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<int?>("IntervalRestSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("interval_rest_seconds");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("Reps")
                        .HasColumnType("integer")
                        .HasColumnName("reps");

                    b.Property<int>("RestSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("rest_seconds");

                    b.Property<int?>("Rounds")
                        .HasColumnType("integer")
                        .HasColumnName("rounds");

                    b.Property<string>("SectionLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("section_label");

                    b.Property<int>("Sets")
                        .HasColumnType("integer")
                        .HasColumnName("sets");

                    b.Property<int?>("WorkSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("work_seconds");

                    b.Property<Guid>("WorkoutTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_template_id");

                    b.HasKey("Id")
                        .HasName("pk_template_items");

                    b.HasIndex("WorkoutTemplateId")
                        .HasDatabaseName("ix_template_items_workout_template_id");

                    b.ToTable("template_items", "public");
                });

            modelBuilder.Entity("Domain.Workouts.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("ModalityId")
                        .HasColumnType("uuid")
                        .HasColumnName("modality_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerStudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_student_id");

                    b.Property<Guid?>("SourceTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_template_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_workouts");

                    b.HasIndex("ModalityId")
                        .HasDatabaseName("ix_workouts_modality_id");

                    b.HasIndex("TenantId", "OwnerStudentId")
                        .HasDatabaseName("ix_workouts_tenant_id_owner_student_id");

                    b.ToTable("workouts", "public");
                });

            modelBuilder.Entity("Domain.Workouts.WorkoutItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<int?>("IntervalRestSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("interval_rest_seconds");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("ProfessorComment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("professor_comment");

                    b.Property<int>("Reps")
                        .HasColumnType("integer")
                        .HasColumnName("reps");

                    b.Property<int>("RestSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("rest_seconds");

                    b.Property<int?>("Rounds")
                        .HasColumnType("integer")
                        .HasColumnName("rounds");

                    b.Property<string>("SectionLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("section_label");

                    b.Property<int>("Sets")
                        .HasColumnType("integer")
                        .HasColumnName("sets");

                    b.Property<int?>("WorkSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("work_seconds");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_id");

                    b.HasKey("Id")
                        .HasName("pk_workout_items");

                    b.HasIndex("WorkoutId")
                        .HasDatabaseName("ix_workout_items_workout_id");

                    b.ToTable("workout_items", "public");
                });

            modelBuilder.Entity("Domain.Workouts.WorkoutTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatorNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("creator_notes");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_default");

                    b.Property<Guid?>("ModalityId")
                        .HasColumnType("uuid")
                        .HasColumnName("modality_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_workout_templates");

                    b.HasIndex("ModalityId")
                        .HasDatabaseName("ix_workout_templates_modality_id");

                    b.HasIndex("TenantId", "IsSystemDefault")
                        .HasDatabaseName("ix_workout_templates_tenant_id_is_system_default");

                    b.ToTable("workout_templates", "public");
                });

            modelBuilder.Entity("Domain.Execution.ExerciseNote", b =>
                {
                    b.HasOne("Domain.Execution.WorkoutSession", null)
                        .WithMany("Notes")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_notes_workout_sessions_workout_session_id");
                });

            modelBuilder.Entity("Domain.Exercises.Exercise", b =>
                {
                    b.HasOne("Domain.Modalities.Modality", "Modality")
                        .WithMany()
                        .HasForeignKey("ModalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exercises_modalities_modality_id");

                    b.Navigation("Modality");
                });

            modelBuilder.Entity("Domain.Exercises.ExerciseMedia", b =>
                {
                    b.HasOne("Domain.Exercises.Exercise", null)
                        .WithMany("Media")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_media_exercises_exercise_id");
                });

            modelBuilder.Entity("Domain.Students.HealthObservation", b =>
                {
                    b.HasOne("Domain.Students.StudentProfile", null)
                        .WithMany("HealthObservations")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_health_observations_student_profiles_student_profile_id");
                });

            modelBuilder.Entity("Domain.Students.StudentNote", b =>
                {
                    b.HasOne("Domain.Students.StudentProfile", null)
                        .WithMany("Notes")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_notes_student_profiles_student_profile_id");
                });

            modelBuilder.Entity("Domain.Workouts.TemplateItem", b =>
                {
                    b.HasOne("Domain.Workouts.WorkoutTemplate", null)
                        .WithMany("Items")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_items_workout_templates_workout_template_id");
                });

            modelBuilder.Entity("Domain.Workouts.Workout", b =>
                {
                    b.HasOne("Domain.Modalities.Modality", "Modality")
                        .WithMany()
                        .HasForeignKey("ModalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_workouts_modalities_modality_id");

                    b.Navigation("Modality");
                });

            modelBuilder.Entity("Domain.Workouts.WorkoutItem", b =>
                {
                    b.HasOne("Domain.Workouts.Workout", null)
                        .WithMany("Items")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workout_items_workouts_workout_id");
                });

            modelBuilder.Entity("Domain.Workouts.WorkoutTemplate", b =>
                {
                    b.HasOne("Domain.Modalities.Modality", "Modality")
                        .WithMany()
                        .HasForeignKey("ModalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_workout_templates_modalities_modality_id");

                    b.Navigation("Modality");
                });

            modelBuilder.Entity("Domain.Execution.WorkoutSession", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Domain.Exercises.Exercise", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("Domain.Students.StudentProfile", b =>
                {
                    b.Navigation("HealthObservations");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Domain.Workouts.Workout", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Domain.Workouts.WorkoutTemplate", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
